### ISSUE TITLE
"Too many open files"

### ISSUE THREAD

**Issue by XAMEUS** [XAMEUS/Two-dimensional-Cellular-Automaton#2]
Là on a presque le truc de base.

Teste le avec le fnc.dimacs qui a été généré, j'obtiens une erreur :

```
Fatal error: exception Sys_error("fnc.dimacs.tmp: Too many open files")
```

Le fichier gen contient bien des générations stables, il faut relancer le programme pour continuer à en trouver d'autres...

**Comment by PierrickJACQUETTE** [comment]
Dans gens tu veux dire ?

**Comment by XAMEUS** [comment]
Oui

**Comment by XAMEUS** [comment]
Résolu
